# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './plugin_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1244, 871)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(216, 216, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 12, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 216, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 12, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 12, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 12, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setIconSize(QtCore.QSize(40, 40))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ch1Viewer = PlotWidget(self.centralwidget)
        self.ch1Viewer.setGeometry(QtCore.QRect(350, 100, 381, 341))
        self.ch1Viewer.setObjectName("ch1Viewer")
        self.numSlicesInput = QtWidgets.QLineEdit(self.centralwidget)
        self.numSlicesInput.setGeometry(QtCore.QRect(190, 100, 119, 39))
        self.numSlicesInput.setObjectName("numSlicesInput")
        self.ch1ViewButton = QtWidgets.QCheckBox(self.centralwidget)
        self.ch1ViewButton.setGeometry(QtCore.QRect(40, 190, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ch1ViewButton.setFont(font)
        self.ch1ViewButton.setObjectName("ch1ViewButton")
        self.ch2ViewButton = QtWidgets.QCheckBox(self.centralwidget)
        self.ch2ViewButton.setGeometry(QtCore.QRect(40, 260, 211, 37))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 143, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 143, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 143, 143))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.ch2ViewButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ch2ViewButton.setFont(font)
        self.ch2ViewButton.setObjectName("ch2ViewButton")
        self.numSlicesLabel = QtWidgets.QLabel(self.centralwidget)
        self.numSlicesLabel.setGeometry(QtCore.QRect(40, 100, 131, 33))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.numSlicesLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numSlicesLabel.setFont(font)
        self.numSlicesLabel.setObjectName("numSlicesLabel")
        self.ch2Viewer = PlotWidget(self.centralwidget)
        self.ch2Viewer.setGeometry(QtCore.QRect(770, 100, 381, 341))
        self.ch2Viewer.setObjectName("ch2Viewer")
        self.loadEBROIsButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadEBROIsButton.setGeometry(QtCore.QRect(20, 320, 131, 51))
        self.loadEBROIsButton.setObjectName("loadEBROIsButton")
        self.clearROIsButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearROIsButton.setGeometry(QtCore.QRect(20, 390, 131, 51))
        self.clearROIsButton.setObjectName("clearROIsButton")
        self.loadPBROIsButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadPBROIsButton.setGeometry(QtCore.QRect(180, 320, 131, 51))
        self.loadPBROIsButton.setObjectName("loadPBROIsButton")
        self.roiLockCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.roiLockCheckBox.setGeometry(QtCore.QRect(180, 400, 101, 31))
        self.roiLockCheckBox.setObjectName("roiLockCheckBox")
        self.fluorescenceCalcLabel = QtWidgets.QLabel(self.centralwidget)
        self.fluorescenceCalcLabel.setGeometry(QtCore.QRect(20, 470, 191, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.fluorescenceCalcLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fluorescenceCalcLabel.setFont(font)
        self.fluorescenceCalcLabel.setObjectName("fluorescenceCalcLabel")
        self.functionalChLabel = QtWidgets.QLabel(self.centralwidget)
        self.functionalChLabel.setGeometry(QtCore.QRect(90, 520, 141, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.functionalChLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.functionalChLabel.setFont(font)
        self.functionalChLabel.setObjectName("functionalChLabel")
        self.staticChLabel = QtWidgets.QLabel(self.centralwidget)
        self.staticChLabel.setGeometry(QtCore.QRect(90, 570, 141, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.staticChLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.staticChLabel.setFont(font)
        self.staticChLabel.setObjectName("staticChLabel")
        self.ch1FuncChanButton = QtWidgets.QRadioButton(self.centralwidget)
        self.ch1FuncChanButton.setGeometry(QtCore.QRect(260, 520, 170, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch1FuncChanButton.sizePolicy().hasHeightForWidth())
        self.ch1FuncChanButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ch1FuncChanButton.setFont(font)
        self.ch1FuncChanButton.setIconSize(QtCore.QSize(60, 60))
        self.ch1FuncChanButton.setObjectName("ch1FuncChanButton")
        self.functionalChButtonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.functionalChButtonGroup.setObjectName("functionalChButtonGroup")
        self.functionalChButtonGroup.addButton(self.ch1FuncChanButton)
        self.ch2FuncChanButton = QtWidgets.QRadioButton(self.centralwidget)
        self.ch2FuncChanButton.setGeometry(QtCore.QRect(450, 520, 181, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch2FuncChanButton.sizePolicy().hasHeightForWidth())
        self.ch2FuncChanButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ch2FuncChanButton.setFont(font)
        self.ch2FuncChanButton.setIconSize(QtCore.QSize(60, 60))
        self.ch2FuncChanButton.setObjectName("ch2FuncChanButton")
        self.functionalChButtonGroup.addButton(self.ch2FuncChanButton)
        self.ch2StaticChanButton = QtWidgets.QRadioButton(self.centralwidget)
        self.ch2StaticChanButton.setGeometry(QtCore.QRect(450, 570, 181, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch2StaticChanButton.sizePolicy().hasHeightForWidth())
        self.ch2StaticChanButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ch2StaticChanButton.setFont(font)
        self.ch2StaticChanButton.setIconSize(QtCore.QSize(60, 60))
        self.ch2StaticChanButton.setObjectName("ch2StaticChanButton")
        self.staticChButtonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.staticChButtonGroup.setObjectName("staticChButtonGroup")
        self.staticChButtonGroup.addButton(self.ch2StaticChanButton)
        self.ch1StaticChanButton = QtWidgets.QRadioButton(self.centralwidget)
        self.ch1StaticChanButton.setGeometry(QtCore.QRect(260, 570, 170, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ch1StaticChanButton.sizePolicy().hasHeightForWidth())
        self.ch1StaticChanButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ch1StaticChanButton.setFont(font)
        self.ch1StaticChanButton.setIconSize(QtCore.QSize(60, 60))
        self.ch1StaticChanButton.setObjectName("ch1StaticChanButton")
        self.staticChButtonGroup.addButton(self.ch1StaticChanButton)
        # self.functionalChReset = QtWidgets.QPushButton(self.centralwidget)
        # self.functionalChReset.setGeometry(QtCore.QRect(660, 520, 71, 31))
        # self.functionalChReset.setObjectName("functionalChReset")
        # self.staticChReset = QtWidgets.QPushButton(self.centralwidget)
        # self.staticChReset.setGeometry(QtCore.QRect(660, 570, 71, 31))
        # self.staticChReset.setObjectName("staticChReset")
        self.viewChsLabel = QtWidgets.QLabel(self.centralwidget)
        self.viewChsLabel.setGeometry(QtCore.QRect(20, 150, 221, 33))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.viewChsLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.viewChsLabel.setFont(font)
        self.viewChsLabel.setObjectName("viewChsLabel")
        self.streamDataCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.streamDataCheckBox.setGeometry(QtCore.QRect(780, 540, 211, 37))
        self.streamDataCheckBox.setObjectName("streamDataCheckBox")
        self.ch1Label = QtWidgets.QLabel(self.centralwidget)
        self.ch1Label.setGeometry(QtCore.QRect(350, 60, 191, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.ch1Label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ch1Label.setFont(font)
        self.ch1Label.setObjectName("ch1Label")
        self.ch2Label = QtWidgets.QLabel(self.centralwidget)
        self.ch2Label.setGeometry(QtCore.QRect(770, 60, 191, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(195, 195, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.ch2Label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ch2Label.setFont(font)
        self.ch2Label.setObjectName("ch2Label")
        self.bumpViewer = PlotWidget(self.centralwidget)
        self.bumpViewer.setGeometry(QtCore.QRect(320, 620, 841, 192))
        self.bumpViewer.setObjectName("graphicsView")
        self.roiIndexLabel = QtWidgets.QLabel(self.centralwidget)
        self.roiIndexLabel.setGeometry(QtCore.QRect(270, 700, 41, 33))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.roiIndexLabel.setFont(font)
        self.roiIndexLabel.setObjectName("roiIndexLabel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(710, 810, 114, 33))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ch1ViewButton.setText(_translate("MainWindow", "Channel 1 (red PMT)"))
        self.ch2ViewButton.setText(_translate("MainWindow", "Channel 2 (green PMT)"))
        self.numSlicesLabel.setText(_translate("MainWindow", "Number of Slices:"))
        self.loadEBROIsButton.setText(_translate("MainWindow", "Load EB ROIs"))
        self.clearROIsButton.setText(_translate("MainWindow", "Clear ROIs"))
        self.loadPBROIsButton.setText(_translate("MainWindow", "Load PB ROIs"))
        self.roiLockCheckBox.setText(_translate("MainWindow", "Lock ROIs"))
        self.fluorescenceCalcLabel.setText(_translate("MainWindow", "Live Bump Calculation:"))
        self.functionalChLabel.setText(_translate("MainWindow", "Functional Channel:"))
        self.staticChLabel.setText(_translate("MainWindow", "Baseline Channel:"))
        self.ch1FuncChanButton.setText(_translate("MainWindow", "Channel 1 (red PMT)"))
        self.ch2FuncChanButton.setText(_translate("MainWindow", "Channel 2 (green PMT)"))
        self.ch2StaticChanButton.setText(_translate("MainWindow", "Channel 2 (green PMT)"))
        self.ch1StaticChanButton.setText(_translate("MainWindow", "Channel 1 (red PMT)"))
        # self.functionalChReset.setText(_translate("MainWindow", "reset"))
        # self.staticChReset.setText(_translate("MainWindow", "reset"))
        self.viewChsLabel.setText(_translate("MainWindow", "View live approx Z-Projection:"))
        self.streamDataCheckBox.setText(_translate("MainWindow", "Stream Bump Data"))
        self.ch1Label.setText(_translate("MainWindow", "Channel 1 (red PMT)"))
        self.ch2Label.setText(_translate("MainWindow", "Channel 2 (green PMT)"))
        self.roiIndexLabel.setText(_translate("MainWindow", "ROI #"))
        self.label_2.setText(_translate("MainWindow", "Time"))

from pyqtgraph import ImageView, PlotWidget, ImageItem